export const iconImages = {
  email: require('./assets/icons/email.png'),
  pswd: require('./assets/icons/pswd.png'),
  user: require('./assets/icons/user.png'),
  bottomArrow: require('./assets/icons/bottomArrow.png'),
  calendarRight: require('./assets/icons/calendarRight.png'),
  calendarLeft: require('./assets/icons/calendarLeft.png'),
  checked: require('./assets/icons/checked.png'),
  email2: require('./assets/icons/email2.png'),
  kakao: require('./assets/icons/kakao.png'),
  link: require('./assets/icons/link.png'),
  nextArrow: require('./assets/icons/nextArrow.png'),
  nextArrow2: require('./assets/icons/nextArrow2.png'),
  nonchecked: require('./assets/icons/nonchecked.png'),
  photo_select: require('./assets/icons/photo_select.png'),
  plusEtc: require('./assets/icons/plusEtc.png'),
  preBtn: require('./assets/icons/preBtn.png'),
  prevArrow: require('./assets/icons/prevArrow.png'),
  profileEdit: require('./assets/icons/profileEdit.png'),
  question_icon: require('./assets/icons/question_icon.png'),
  rightArrow: require('./assets/icons/rightArrow.png'),
  signout: require('./assets/icons/signout.png'),
  topArrow: require('./assets/icons/topArrow.png'),
  userbaseicon: require('./assets/icons/userbaseicon.png'),
};

export const homeImages = {
  challen: require('./assets/home/challen.png'),
  exclamation: require('./assets/home/exclamation.png'),
  home: require('./assets/home/home.png'),
  home1: require('./assets/home/home1.png'),
  home2: require('./assets/home/home2.png'),
  home3: require('./assets/home/home3.png'),
  home4: require('./assets/home/home4.png'),
  union: require('./assets/home/union.png'),
};

export const habitImages = {
  alo0 : require('./assets/habit/alo0.png'),
  alo5 : require('./assets/habit/alo5.png'),
  alo10 : require('./assets/habit/alo10.png'),
  alo15 : require('./assets/habit/alo15.png'),
  alo20 : require('./assets/habit/alo20.png'),
  alo25 : require('./assets/habit/alo25.png'),
  alo30 : require('./assets/habit/alo30.png'),
  alo35 : require('./assets/habit/alo35.png'),
  alo40 : require('./assets/habit/alo40.png'),
  alo45 : require('./assets/habit/alo45.png'),
  alo50 : require('./assets/habit/alo50.png'),
  alo55 : require('./assets/habit/alo55.png'),
  alo60 : require('./assets/habit/alo60.png'),
  alo65 : require('./assets/habit/alo65.png'),
  alo70 : require('./assets/habit/alo70.png'),
  alo75 : require('./assets/habit/alo75.png'),
  alo80 : require('./assets/habit/alo80.png'),
  alo85 : require('./assets/habit/alo85.png'),
  alo90 : require('./assets/habit/alo90.png'),
  alo95 : require('./assets/habit/alo95.png'),
  alo100 : require('./assets/habit/alo100.png'),
  tog0 : require('./assets/habit/tog0.png'),
  tog5 : require('./assets/habit/tog5.png'),
  tog10 : require('./assets/habit/tog10.png'),
  tog15 : require('./assets/habit/tog15.png'),
  tog20 : require('./assets/habit/tog20.png'),
  tog25 : require('./assets/habit/tog25.png'),
  tog30 : require('./assets/habit/tog30.png'),
  tog35 : require('./assets/habit/tog35.png'),
  tog40 : require('./assets/habit/tog40.png'),
  tog45 : require('./assets/habit/tog45.png'),
  tog50 : require('./assets/habit/tog50.png'),
  tog55 : require('./assets/habit/tog55.png'),
  tog60 : require('./assets/habit/tog60.png'),
  tog65 : require('./assets/habit/tog65.png'),
  tog70 : require('./assets/habit/tog70.png'),
  tog75 : require('./assets/habit/tog75.png'),
  tog80 : require('./assets/habit/tog80.png'),
  tog85 : require('./assets/habit/tog85.png'),
  tog90 : require('./assets/habit/tog90.png'),
  tog95 : require('./assets/habit/tog95.png'),
  tog100 : require('./assets/habit/tog100.png'),
  alone_add : require('./assets/habit/alone_add.png'),
  alone_grapes : require('./assets/habit/alone_grapes.png'),
  aloneHeader : require('./assets/habit/aloneHeader.png'),
  aloneHeader2 : require('./assets/habit/aloneHeader2.png'),
  ellipse : require('./assets/habit/ellipse.png'),
  habit1 : require('./assets/habit/habit1.png'),
  habit2 : require('./assets/habit/habit2.png'),
  habit3 : require('./assets/habit/habit3.png'),
  habit4 : require('./assets/habit/habit4.png'),
  habit5 : require('./assets/habit/habit5.png'),
  non0 : require('./assets/habit/non0.png'),
  selectHeader : require('./assets/habit/selectHeader.png'),
  together_add : require('./assets/habit/together_add.png'),
  together_grapes : require('./assets/habit/together_grapes.png'),
  togetherCheck : require('./assets/habit/togetherCheck.png'),
  togetherHeader : require('./assets/habit/togetherHeader.png'),
};

export const emojiImages = {
    emoji1: require('./assets/emoji/emoji1.png'),
    emoji2: require('./assets/emoji/emoji2.png'),
    emoji3: require('./assets/emoji/emoji3.png'),
    emoji4: require('./assets/emoji/emoji4.png'),
    emoji5: require('./assets/emoji/emoji5.png'),
    emoji6: require('./assets/emoji/emoji6.png'),
    emoji7: require('./assets/emoji/emoji7.png'),
    emoji8: require('./assets/emoji/emoji8.png'),
    emoji9: require('./assets/emoji/emoji9.png'),
    emoji10: require('./assets/emoji/emoji10.png'),
    emoji11: require('./assets/emoji/emoji11.png'),
    emoji12: require('./assets/emoji/emoji12.png'),
    bad: require('./assets/emoji/bad.png'),
    smile: require('./assets/emoji/smile.png'),
    soso: require('./assets/emoji/soso.png'),
  };

  export const bottomsImages = {
    calendar_nonactive: require('./assets/bottoms/calendar_nonactive.png'),
    challenge_active: require('./assets/bottoms/challenge_active.png'),
    challenge_nonactive: require('./assets/bottoms/challenge_nonactive.png'),
    feed_active: require('./assets/bottoms/feed_active.png'),
    feed_nonactive: require('./assets/bottoms/feed_nonactive.png'),
    home_active: require('./assets/bottoms/home_active.png'),
    home_nonactive: require('./assets/bottoms/home_nonactive.png'),
    user_active: require('./assets/bottoms/user_active.png'),
    user_nonactive: require('./assets/bottoms/user_nonactive.png'),
  };

  export const backgroundImages = {
    back1 : require('./assets/background/back1.png'),
    back2 : require('./assets/background/back2.png'),
    back3 : require('./assets/background/back3.png'),
    back4 : require('./assets/background/back4.png'),
    back5 : require('./assets/background/back5.png'),
    back6 : require('./assets/background/back6.png'),
    back7 : require('./assets/background/back7.png'),
    back8 : require('./assets/background/back8.png'),
    back9 : require('./assets/background/back9.png'),
    back10 : require('./assets/background/back10.png'),
    back11 : require('./assets/background/back11.png'),
    back12 : require('./assets/background/back12.png'),
    back13 : require('./assets/background/back13.png'),
    back14 : require('./assets/background/back14.png'),
    back15 : require('./assets/background/back15.png'),
  };

  export const roomsImages = {
    room1 : require('./assets/rooms/room1.png'),
    room2 : require('./assets/rooms/room2.png'),
    room3 : require('./assets/rooms/room3.png'),
    room4 : require('./assets/rooms/room4.png'),
    room5 : require('./assets/rooms/room5.png'),
    room6 : require('./assets/rooms/room6.png'),
    room7 : require('./assets/rooms/room7.png'),
    room8 : require('./assets/rooms/room8.png'),
    room9 : require('./assets/rooms/room9.png'),
    room10 : require('./assets/rooms/room10.png'),
    room11 : require('./assets/rooms/room11.png'),
    room12 : require('./assets/rooms/room12.png'),
    room13 : require('./assets/rooms/room13.png'),
    room14 : require('./assets/rooms/room14.png'),
    room15 : require('./assets/rooms/room15.png'),
    thum1 : require('./assets/rooms/thum1.png'),
    thum2 : require('./assets/rooms/thum2.png'),
    thum3 : require('./assets/rooms/thum3.png'),
    thum4 : require('./assets/rooms/thum4.png'),
    thum5 : require('./assets/rooms/thum5.png'),
    thum6 : require('./assets/rooms/thum6.png'),
    thum7 : require('./assets/rooms/thum7.png'),
    thum8 : require('./assets/rooms/thum8.png'),
    thum9 : require('./assets/rooms/thum9.png'),
    thum10 : require('./assets/rooms/thum10.png'),
    thum11 : require('./assets/rooms/thum11.png'),
    thum12 : require('./assets/rooms/thum12.png'),
    thum13 : require('./assets/rooms/thum13.png'),
    thum14 : require('./assets/rooms/thum14.png'),
    thum15 : require('./assets/rooms/thum15.png'),
  };

  export const tabsImages = {
    dot0 : require('./assets/tabs/dot0.png'),
    dot1 : require('./assets/tabs/dot1.png'),
    dot2 : require('./assets/tabs/dot2.png'),
    dot3 : require('./assets/tabs/dot3.png'),
  };